// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD96VNxTgDF_pk2jxvA01qmkllbnSlSlGA',
    appId: '1:1076686190000:web:8b9ad5b210d525631a9275',
    messagingSenderId: '1076686190000',
    projectId: 'returna-66ebf',
    authDomain: 'returna-66ebf.firebaseapp.com',
    storageBucket: 'returna-66ebf.firebasestorage.app',
    measurementId: 'G-8RQDM7RB2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfckprUkcxSX6du9Al4w3UE8tqwXMR-gA',
    appId: '1:1076686190000:android:1446e0b517266a5a1a9275',
    messagingSenderId: '1076686190000',
    projectId: 'returna-66ebf',
    storageBucket: 'returna-66ebf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgMPFtpP889MPpPZwrxIA46Hdih4TIHUM',
    appId: '1:1076686190000:ios:9f0d23fa565b357a1a9275',
    messagingSenderId: '1076686190000',
    projectId: 'returna-66ebf',
    storageBucket: 'returna-66ebf.firebasestorage.app',
    iosBundleId: 'com.example.errasoft',
  );
}
